# Inspired from Spacy attrs structs.


class Attributes:
    """Class holding Attributes Id's for Lexical attributes."""

    (
        NULL_ATTR,  # NULL_ATTR with value 0, is not used.
        ID,
        ORTH,
        LOWER,
        NORM,
        SHAPE,
        PREFIX,
        SUFFIX,
        LENGTH,
        LANG,
        IS_ALPHA,
        IS_ASCII,
        IS_DIGIT,
        IS_LOWER,
        IS_PUNCT,
        IS_SPACE,
        IS_TITLE,
        IS_UPPER,
        LIKE_URL,
        LIKE_NUM,
        LIKE_EMAIL,
        IS_STOP,
        IS_OOV,
        IS_BRACKET,
        IS_QUOTE,
        IS_LEFT_PUNCT,
        IS_RIGHT_PUNCT,
        IS_CURRENCY,
        Flag28,
        Flag29,
        Flag30,
        Flag31,
        Flag32,
        Flag33,
        Flag34,
        Flag35,
        Flag36,
        Flag37,
        Flag38,
        Flag39,
        Flag40,
        Flag41,
        Flag42,
        Flag43,
        Flag44,
        Flag45,
        Flag46,
        Flag47,
        Flag48,
        Flag49,
        Flag50,
        Flag51,
        Flag52,
        Flag53,
        Flag54,
        Flag55,
        Flag56,
        Flag57,
        Flag58,
        Flag59,
        Flag60,
        Flag61,
        Flag62,
        Flag63,
        Flag64,
        Flag65,
        Flag66,
        Flag67,
        Flag68,
    ) = range(69)
